blank_issues_enabled: true
contact_links:
  - name: Report A Translation Issue On The Legis Link Website
    url: https://crowdin.com/project/legis-link
    about: 'Is something wrong with a specific translation? Can a language be improved? Do you have suggestions?'
